start_recirculation:
  name: Start Recirculation
  description: Start recirculation on the water heater.
  target:
    entity:
      domain: water_heater
  fields:
    recirculation_minutes:
      name: Recirculation minutes
      description: The time to recirculate in minutes.
      required: false
      default: "5"
      example: "15"
      selector:
        select:
          options:
            - label: "5 minutes"
              value: "5"
            - label: "15 minutes"
              value: "15"
            - label: "30 minutes"
              value: "30"
            - label: "45 minutes"
              value: "45"
            - label: "1 hour"
              value: "60"
            - label: "1 hour 15 minutes"
              value: "75"
            - label: "1 hour 30 minutes"
              value: "90"
            - label: "1 hour 45 minutes"
              value: "105"
            - label: "2 hours"
              value: "120"
            - label: "2 hours 15 minutes"
              value: "135"
            - label: "2 hours 30 minutes"
              value: "150"
            - label: "2 hours 45 minutes"
              value: "165"
            - label: "3 hours"
              value: "180"
            - label: "3 hours 15 minutes"
              value: "195"
            - label: "3 hours 30 minutes"
              value: "210"
            - label: "3 hours 45 minutes"
              value: "225"
            - label: "4 hours"
              value: "240"
            - label: "4 hours 15 minutes"
              value: "255"
            - label: "4 hours 30 minutes"
              value: "270"
            - label: "4 hours 45 minutes"
              value: "285"
            - label: "5 hours"
              value: "300"
stop_recirculation:
  name: Stop Recirculation
  description: Stop recirculation on the water heater.
  target:
    entity:
      domain: water_heater